### ISSUE TITLE
Resolve deployment of forked google-map-react module

### ISSUE THREAD

**Issue by PKiechl** [UZHASE/bnbexplorer-frontend#46]
**Description of Problem:**
We forked an existing npm module to introduce support for multiple heatmaps. the code itself works nicely, however, including the forked repo in the deployed heroku build is problematic, as it fails to include it from the forked repo.

**Attempts so far:**

- postinstall script in package.json, works locally (from what we can tell)
- other solutions have been attempted but all failed

**Temporary fix:**
Including the source files of the forked module directly in this repository, so that we are not hindered in development. The goal is still to ultimately get it working as a npm module, but it is of less priority than developing the application itself. In the worst case, the forked module's source files will remain directly included in this repo.

**Comment by fabiank0** [comment]
Removed the local files, to pull the library from a separate repository now.
