### ISSUE TITLE
listing details: images where found

### ISSUE THREAD

**Issue by PKiechl** [UZHASE/bnbexplorer-frontend#80]

**Comment by cdeiac** [comment]
Listing images are now available, here is an example: https://bnbexplorer-backend.herokuapp.com/api/v1/airbnb-explorer/listings/30764990
There are some Listings that do not have any images.

**Comment by fabiank0** [comment]
@cdeiac Thanks! We're working on it right now :) 
![Uploading Screenshot 2021-05-15 at 17.06.01.png…]()
